---
- name: local install
  hosts: localhost
  become: yes
  become_method: sudo


  pre_tasks:
    - name: import custom variables
      include_vars: "{{ item }}"
      with_items:
        - "{{ inventory_dir }}/vault/secrets.yml"
        - "{{ inventory_dir }}/custom_vars.yml"

      when: item is exists
      tags:
        - account
        - user
        - gitconfig
        - sudo
        - sudoer
        - skel
        - sshkeys
        - samba
        - atom
        - oh-my-zsh
        - zsh
        - aws
        - google-cloud-sdk
        - gcp-sdk
        - terraform
        - packer
        - kops
        - kubectl
        - helm

  roles:
    - locales
    - docker
    - account
    - samba
    - dnsmasq
    - json_yaml_tools
    - packer
    - terraform
    - vagrant
    - oh-my-zsh
    - kvm
    - minikube
    - kops
    - kubectl
    - helm
    - aws
    - google-cloud-sdk
    - role: gantsign.golang
      tags:
        - golang
    - role: geerlingguy.nodejs
      tags:
        - nodejs
        - node
    - role: oefenweb.yarn
      tags:
        - nodejs
        - node
        - yarn
    - role: gantsign.atom
      users: "{{ atom_users }}"
      tags:
        - atom
    - role: ngetchell.vscode
      tags:
        - vscode
    # - role: jdauphant.sublimetext
    #   tags:
    #     - sublimetext
    #     - sublime
