---
- name: local install
  hosts: localhost
  become: yes
  become_method: sudo

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - "{{ inventory_dir }}/vault/secrets.yml"
        - "{{ inventory_dir }}/custom_vars.yml"

      when: item is exists
      tags:
        - account
        - user
        - sudo
        - sudoer
        - skel
        - sshkeys
        - samba
        - atom
        - oh-my-zsh
        - zsh
        - aws
        - google-cloud-sdk
        - gcp-sdk

  roles:
    - locales
    - docker
    - account
    - samba
    - dnsmasq
    - json_yaml_tools
    - packer
    - terraform
    - vagrant
    - oh-my-zsh
    - kvm
    - minikube
    - kops
    - kubectl
    - helm
    - role: gantsign.atom
      users: "{{ atom_users }}"
      tags:
        - atom
    - jdauphant.sublimetext
    - aws
    - google-cloud-sdk
