---
- name: local install
  hosts: localhost
  become: yes
  become_method: sudo

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - "{{ inventory_dir }}/vault/secrets.yml"
        - "{{ inventory_dir }}/custom_vars.yml"

      when: item|exists
      tags:
        - account
        - user
        - sudo
        - sudoer
        - skel
        - sshkeys
        - samba
        - atom
        - oh-my-zsh
        - zsh
        - aws

  roles:
    - locales
    - docker
    - account
    - samba
    - dnsmasq
    - packer
    - terraform
    - vagrant
    - oh-my-zsh
    - kops
    - kubectl
    - atom
    - aws
